### ISSUE TITLE
cache busting for demos by installing hamster-html

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/website#10]
hamster-html is a static website builder, and it has this special cache-busting feature that fixes caching problems for users.

- `website` repo and `humanoid` repo already use hamster-html to build their web pages
- we need to apply this same pattern, of using hamster-html to build a website with cache busting, onto every demo repo that we have (nubs, mule, etc)
- the github workflows will likely need to be updated, at least `release.yaml`

**Comment by PaulAroo** [comment]
> website repo and humanoid repo already use hamster-html to build their web pages

humanoid doesn't have cache busting implemented yet, will set it up tho
